name: google_maps_place_picker_mb
description: A Flutter plugin which provides 'Picking Place' using Google Maps
  widget. (MB version)
version: 2.0.0-mb.16
homepage: https://github.com/martin-braun/google_maps_place_picker_mb

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^8.2.0
  google_api_headers: ^1.1.1
  google_maps_flutter: ^2.1.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  http: ^0.13.4
  location: ^4.3.0
  provider: ^6.0.1
  tuple: ^2.0.0
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
