name: google_maps_place_picker
description: A Flutter plugin which provides 'Picking Place' using Google Maps widget.
version: 1.0.1
homepage: https://github.com/fysoul17/google_maps_place_picker

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.0.1
  geolocator: ^6.0.0+4
  permission_handler: ^5.0.1+1
  provider: ^4.0.1
  google_api_headers: ">=0.1.0 <1.0.0"
  google_maps_webservice: ^0.0.19
  tuple: ^1.0.3
  http: ^0.12.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
